### ISSUE TITLE
More instructions about training PET/CT, motion correction and undersampled MRI reconstruction

### ISSUE THREAD

**Issue by linhlpv** [ExplainableML/UncerGuidedI2I#1]
Hi, thank you so much about amazing work.
I am very interesting in this topic and I want to reproduce experiments. I found that you have given some instructions in README file but I still stuck with preparing data part. Could you write more and clear instructions about how to run this repo.
Thank you so much again and hope to hear from you soon.

**Comment by udion** [comment]
Hi,
Please check the notebooks in data directory.

Also have a look at Dataloader and Dataset calasses (ds.py) in src to craft your own dataset.

The basic idea is that you need to be able to load a pair of images (input and output). The specifics will really depend on the applications.
