### ISSUE TITLE
uncertainty map is not computed

### ISSUE THREAD

**Issue by hellopipu** [ExplainableML/UncerGuidedI2I#3]
Hi,

Thanks for sharing the code for your great work here!

I have a question. In your paper, for each Generator (except the last one),  the output is the concatenation of uncertainty map and the rec img, which is described in Fig. 1 and equation (3),(4) in your paper.

But in your [code](https://github.com/ExplainableML/UncerGuidedI2I/blob/cc4a4e2d0b84e97b072534b46337d7c7a50d18e0/src/utils.py#L160), the output is the concatenation of  rec img, alpha, beta and the original input img. 

Looking forward to your reply. Thanks.

**Comment by udion** [comment]
Hi, 
uncertainty map is the function of alpha, beta.

We tried many combinations of including attention -- computing uncertainty maps explicitly then using it, or passing raw alpha/beta maps -- we found all such combinations perform roughly the same. The code has the simplest implementation that passes raw alpha/beta as concatenation.

**Comment by hellopipu** [comment]
Thanks, I get it.
