### ISSUE TITLE
About loading datasets

### ISSUE THREAD

**Issue by 2805413893** [ExplainableML/UncerGuidedI2I#6]
Dear author
 Hello！ I found that the process of how to load the dataset is missing in the utils.py file during the reproduction process. I am very confused, and I don't know how to place and load the dataset. I hope you can answer it.

**Comment by udion** [comment]
Hi,
Please check the notebooks in data directory.

Also have a look at Dataloader and Dataset calasses (ds.py) in src to craft your own dataset.

The basic idea is that you need to be able to load a pair of images (input and output). The specifics will really depend on the applications.

**Comment by 2805413893** [comment]
> Hi, Please check the notebooks in data directory.
> 
> Also have a look at Dataloader and Dataset calasses (ds.py) in src to craft your own dataset.
> 
> The basic idea is that you need to be able to load a pair of images (input and output). The specifics will really depend on the applications.
Sorry, I can not find dataloader and data classes (ds.py) in src. I am confused.I only find PairImagebs_w_nameList class.
